### ISSUE TITLE
Set up deployment

### ISSUE THREAD

**Issue by iiegn** [commul/fromthepage_old#4]
Once #1 #2 #3 have been resolved...

set up (semi-)automated deployment - likely, with [phusion passanger](https://www.phusionpassenger.com/).

**Comment by iiegn** [comment]
see http://blog.scoutapp.com/articles/2017/02/10/which-ruby-app-server-is-right-for-you for a comparison of 
 - unicorn
 - puma
 - passanger

hm, puma?

hey, @nadezdaalexandrovna do you have experience with any of these three app servers?

**Comment by nadezdaalexandrovna** [comment]
No, I don't. 

    Le Vendredi 7 juillet 2017 12h00, egon w. stemle <notifications@github.com> a écrit :
 

 see http://blog.scoutapp.com/articles/2017/02/10/which-ruby-app-server-is-right-for-you for a comparison of   
   - unicorn
   - puma
   - passanger
hm, puma?hey, @nadezdaalexandrovna do you have experience with any of these three app servers?—

**Comment by iiegn** [comment]
This issue was moved to commul/fromthepage#4
